version = 0.1

[default.deploy.parameters]
stack_name = "oracle-erp-filelock"
s3_bucket = "dcli-oracle-erp-filelock"
s3_prefix = "oracle-erp-filelock"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
disable_rollback = true
image_repositories = []
parameter_overrides = ""
