
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Oracle File Lock Management Lambda

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    Environment:
      Variables:
        S3_BUCKET: dcli-oracle-erp-storage
        DDB_TABLE: FileLocks

Resources:
  OracleFileLockHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler.lambda_handler
      CodeUri: lambda/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:Scan
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::dcli-oracle-erp-storage
                - arn:aws:s3:::dcli-oracle-erp-storage/*

      Events:
        LockAPI:
          Type: Api
          Properties:
            Path: /lock
            Method: post
        UnlockAPI:
          Type: Api
          Properties:
            Path: /unlock
            Method: post
        StatusAPI:
          Type: Api
          Properties:
            Path: /status
            Method: get
        GetUrlAPI:
          Type: Api
          Properties:
            Path: /get-url
            Method: post
        S3FilesAPI:
          Type: Api
          Properties:
            Path: /s3-files
            Method: get
        ListAPI:
          Type: Api
          Properties:
            Path: /list
            Method: get
        UploadAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: post
        VersionsAPI:
        Type: Api
        Properties:
          Path: /versions
          Method: post
      DownloadAPI:
          Type: Api
          Properties:
            Path: /download
            Method: post
        OptionsAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: options

  FileLocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FileLocks
      AttributeDefinitions:
        - AttributeName: filename
          AttributeType: S
      KeySchema:
        - AttributeName: filename
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
